### ISSUE TITLE
TODO : REST API endpoints for the features

### ISSUE THREAD

**Issue by SubhankarDas** [SubhankarDas/diet-plan-api#1]
- [ ] User login and signup

- [ ] User diet preference update

- [ ] Diet generation based on preferences
